# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

permalink: /:year/:month/:title/
paginate: 05 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Daniele Campogiani

disqus: danielecampogiani
description: Daniele Campogiani
author:
  name: Daniele Campogiani
  email: daniele.campogiani@gmail.com
  github: dcampogiani
  twitter: dcampogiani
  pinterest: dcampogiani
  linkedin: danielecampogiani
  bio: Software Engineer
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
